<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <VersionContents>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory).version\version').Split([Environment]::NewLine)[0].Trim())</VersionContents>
    <Version>$(VersionContents)</Version>
    <AssemblyVersion>$(VersionContents).0</AssemblyVersion>
    <FileVersion>$(VersionContents).0</FileVersion>
  </PropertyGroup>
</Project>
